[package]
name = "HW_1_Spatial_Domain_Watermark_Embedding_Implementation"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
dotenvy = "0.15"
jpeg-decoder = "0.3.1"
rand = "0.9.0"
log = "0.4.27"
flexi_logger = "0.29.8"
chrono = "0.4.19"